### PR TITLE
Return paginated content in paginator, and use it for vue-paginator

### LINKED ISSUE #70: Pagination formula needs to be fixed [FOR CONTRIBUTORS]
**Problem**
In the pagination formula there is a problem in knowing what is the total data to be displayed in an array. For example, when you move to page number 3 no data is displayed. This is incorrect, because if you try the API in special `https://ryuanime-api.chrismichael.now.sh/api/v1/letter/a/8`. You will see that there is data up to page 8. That is why there is an error in calculating the total data.

**Code to verify**
```javascript
export const paginator = (items, page, per_page) => {
  var page = page || 1,
  per_page = per_page || 10,
  offset = (page - 1) * per_page,

  paginatedItems = items.slice(offset).slice(0, per_page),
  total_pages = Math.ceil(items.length / per_page),

  paginContent = {
    page: page,
    per_page: per_page,
    pre_page: page - 1 ? page - 1 : null,
    next_page: (total_pages > page) ? page + 1 : null,
    total: items.length,
    total_pages: total_pages,
    data: paginatedItems
  };
  console.log("Paginate Item: ", paginatedItems);
  console.log("Pagin Content: ", paginContent);
  const total = paginContent.total;
  return paginContent.data;
};
```

**Reference link**
`https://github.com/ChrisMichaelPerezSantiago/ryuanime/blob/master/src/frontend/src/store/paginator/index.js`

### PR DESCRIPTION
**Pull request by kinow**
Closes #70 

I think the issue with the pagination is that we are using the `animes.length`. In some cases it may return 20, and having 10 items per page, then we were supposed to pass the value 2 as `page-count`. But instead, we are passing 20.

At least that's my understanding after reading the [component docs](https://github.com/lokyoung/vuejs-paginate). And testing it locally, it appears to work fine for me.

Cheers
Bruno

### CODE REVIEW

File: src/frontend/src/store/paginator/index.js [hunk 1]
```diff
@@ -18,5 +18,5 @@ export const paginator = (items, page, per_page) => {
   console.log("Paginate Item: ", paginatedItems);
   console.log("Pagin Content: ", paginContent);
   const total = paginContent.total;
-  return paginContent.data;
-};
\ No newline at end of file
+  return paginContent;
```
Comment (kinow) [inline src/frontend/src/store/paginator/index.js]: This is the main change. Instead of discarding the `paginContent`, we need to keep it around to have access to the number of pages.

Comment (ChrisMichaelPerezSantiago) [reply src/frontend/src/store/paginator/index.js]: You are correct, the whole object had to be returned. When you pass only the data I do not have access to the total pages.

That was a stupid mistake on my part

Comment (kinow) [reply src/frontend/src/store/paginator/index.js]: Definitely not stupid. To build a complete application like RyuAnime, it's easy to mistake one value for another 👍 and it took me quite some time to realize what was going on. Thanks for review/merging it so quickly! Now responsive layout is the next one.
